// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBFEZUMqCYqUrDTl3x6Xbs-L9-CEtqdjls",
    authDomain: "radarapp-5176c.firebaseapp.com",
    projectId: "radarapp-5176c",
    storageBucket: "radarapp-5176c.firebasestorage.app",
    messagingSenderId: "294284354409",
    appId: "1:294284354409:web:effdd04330d142f882d3f8",
    measurementId: "G-9KS4MH629Q"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyBFEZUMqCYqUrDTl3x6Xbs-L9-CEtqdjls",
    authDomain: "radarapp-5176c.firebaseapp.com",
    projectId: "radarapp-5176c",
    storageBucket: "radarapp-5176c.firebasestorage.app",
    messagingSenderId: "294284354409",
    appId: "1:294284354409:web:effdd04330d142f882d3f8",
    measurementId: "G-9KS4MH629Q"
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyBFEZUMqCYqUrDTl3x6Xbs-L9-CEtqdjls",
    authDomain: "radarapp-5176c.firebaseapp.com",
    projectId: "radarapp-5176c",
    storageBucket: "radarapp-5176c.firebasestorage.app",
    messagingSenderId: "294284354409",
    appId: "1:294284354409:web:effdd04330d142f882d3f8",
    measurementId: "G-9KS4MH629Q"
}
